title:              Doit Man's Blog
email:              doitman.kwon@gmail.com.com
description:        My note, my experience
author:             Doit-Man
baseurl:            ""
url:                "https://doit-man.github.io"
timezone: Asia/Seoul
future: true
# theme: jekyll-theme-clean-blog
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
# Social Profiles
twitter_username:   SBootstrap
github_username:    doit-man
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter:        rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
